export const CATEGORIES = [
  "All Products",
  "Firearms",
  "Ammunition",
  "Defense Apparel",
  "Tactical Supplies",
  "Optics",
  "Communications",
];

export interface Product {
  id: string;
  slug: string;
  name: string;
  category: string;
  image: string;
  description: string;
  specs: { label: string; value: string }[];
  features: string[];
}

export const PRODUCTS: Product[] = [
  { id: "1", slug: "m4a1-carbine", name: "M4A1 Carbine", category: "Firearms", image: "https://placehold.co/600x400/0a0a0a/333?text=M4A1+Carbine", description: "The M4A1 Carbine is a lightweight, air-cooled, gas-operated, magazine-fed assault rifle ideal for military and law enforcement operations.", specs: [{ label: "Caliber", value: "5.56x45mm NATO" }, { label: "Weight", value: "3.0 kg" }, { label: "Barrel Length", value: "370mm" }, { label: "Action", value: "Gas-operated" }], features: ["Full-auto capable", "MIL-STD-1913 rail", "Adjustable stock", "Night vision compatible"] },
  { id: "2", slug: "glock-17-gen5", name: "Glock 17 Gen5", category: "Firearms", image: "https://placehold.co/600x400/0a0a0a/333?text=Glock+17+Gen5", description: "The Glock 17 Gen5 is a striker-fired semi-automatic pistol renowned for reliability and accuracy used globally by law enforcement.", specs: [{ label: "Caliber", value: "9x19mm Parabellum" }, { label: "Weight", value: "0.625 kg" }, { label: "Barrel Length", value: "114mm" }, { label: "Capacity", value: "17+1" }], features: ["Ambidextrous slide stop", "Flared magazine well", "nDLC finish", "Improved trigger"] },
  { id: "3", slug: "5-56-nato-ammo", name: "5.56 NATO Ammunition", category: "Ammunition", image: "https://placehold.co/600x400/0a0a0a/333?text=5.56+NATO+Ammo", description: "High-performance 5.56x45mm NATO ammunition designed for superior accuracy and terminal performance in combat conditions.", specs: [{ label: "Caliber", value: "5.56x45mm" }, { label: "Bullet Weight", value: "62gr" }, { label: "Muzzle Velocity", value: "2970 fps" }, { label: "Packaging", value: "1000 rounds" }], features: ["Green tip penetrator", "Brass case", "Waterproof primer", "Consistent lot accuracy"] },
  { id: "4", slug: "level-iv-plate-carrier", name: "Level IV Plate Carrier", category: "Defense Apparel", image: "https://placehold.co/600x400/0a0a0a/333?text=Plate+Carrier", description: "NIJ Level IV certified plate carrier vest providing maximum ballistic protection for military and law enforcement personnel.", specs: [{ label: "Protection Level", value: "NIJ IV" }, { label: "Weight", value: "8.5 lbs" }, { label: "Material", value: "1000D Cordura" }, { label: "Sizes", value: "S/M/L/XL" }], features: ["Plate pockets front/rear", "MOLLE webbing", "Quick-release system", "Hydration compatible"] },
  { id: "5", slug: "acog-4x32", name: "ACOG 4x32 Scope", category: "Optics", image: "https://placehold.co/600x400/0a0a0a/333?text=ACOG+4x32", description: "Battle-proven Advanced Combat Optical Gunsight providing 4x magnification with illuminated BDC reticle.", specs: [{ label: "Magnification", value: "4x" }, { label: "Objective Lens", value: "32mm" }, { label: "Reticle", value: "BDC for 5.56" }, { label: "Weight", value: "397g" }], features: ["Tritium/fiber illumination", "1913 Picatinny mount", "BAC reticle", "Waterproof/fogproof"] },
  { id: "6", slug: "harris-prc-152a", name: "Harris PRC-152A Radio", category: "Communications", image: "https://placehold.co/600x400/0a0a0a/333?text=PRC-152A+Radio", description: "Multiband handheld tactical radio supporting voice and data communications across a wide frequency range.", specs: [{ label: "Frequency", value: "30-512 MHz" }, { label: "Power", value: "5W" }, { label: "Battery Life", value: "12h" }, { label: "Weight", value: "0.6 kg" }], features: ["Type 1 encryption", "Satellite communications", "GPS receiver", "Bluetooth capable"] },
  { id: "7", slug: "tactical-combat-boot", name: "Tactical Combat Boot", category: "Defense Apparel", image: "https://placehold.co/600x400/0a0a0a/333?text=Combat+Boot", description: "Lightweight tactical combat boot designed for extended field operations with superior ankle support.", specs: [{ label: "Upper", value: "1000D Nylon/Leather" }, { label: "Sole", value: "Vibram" }, { label: "Weight", value: "1.1 kg/pair" }, { label: "Sizes", value: "5-15 (US)" }], features: ["Waterproof membrane", "Flame resistant", "Antimicrobial lining", "Speed lacing"] },
  { id: "8", slug: "m67-fragmentation-grenade", name: "M67 Fragmentation Grenade", category: "Ammunition", image: "https://placehold.co/600x400/0a0a0a/333?text=M67+Grenade", description: "The M67 fragmentation grenade is a standard-issue defensive/offensive hand grenade for military operations.", specs: [{ label: "Weight", value: "0.4 kg" }, { label: "Fill", value: "Composition B" }, { label: "Delay", value: "4-5 seconds" }, { label: "Burst Radius", value: "15m" }], features: ["Steel body", "Spoon safety mechanism", "Color coded", "Mil-spec certified"] },
  { id: "9", slug: "eotech-exps3", name: "EOTech EXPS3 Holographic", category: "Optics", image: "https://placehold.co/600x400/0a0a0a/333?text=EOTech+EXPS3", description: "Premium holographic weapon sight offering 1x magnification with 68 MOA ring/1 MOA dot reticle.", specs: [{ label: "Magnification", value: "1x" }, { label: "Window Size", value: "30x23mm" }, { label: "Battery", value: "CR123A" }, { label: "Weight", value: "226g" }], features: ["Night vision compatible", "Submersible to 10ft", "Side-loading battery", "20 brightness settings"] },
  { id: "10", slug: "multicam-ghillie-suit", name: "MultiCam Ghillie Suit", category: "Defense Apparel", image: "https://placehold.co/600x400/0a0a0a/333?text=Ghillie+Suit", description: "Professional 3D leaf ghillie suit in MultiCam pattern for superior concealment in mixed terrain.", specs: [{ label: "Pattern", value: "MultiCam" }, { label: "Material", value: "Jute/Burlap blend" }, { label: "Coverage", value: "Full body" }, { label: "Weight", value: "2.3 kg" }], features: ["Fire retardant", "Reinforced knee/elbow", "Drag harness", "Customizable foliage"] },
  { id: "11", slug: "m240b-machine-gun", name: "M240B Machine Gun", category: "Firearms", image: "https://placehold.co/600x400/0a0a0a/333?text=M240B", description: "Gas-operated, air-cooled, belt-fed medium machine gun providing sustained fire support.", specs: [{ label: "Caliber", value: "7.62x51mm NATO" }, { label: "Weight", value: "12.5 kg" }, { label: "Rate of Fire", value: "650-950 rpm" }, { label: "Range", value: "3725m" }], features: ["Sustained fire", "Tripod and bipod mount", "Quick-change barrel", "Picatinny rail"] },
  { id: "12", slug: "sordin-supreme-pro", name: "Sordin Supreme Pro X", category: "Tactical Supplies", image: "https://placehold.co/600x400/0a0a0a/333?text=Sordin+Supreme", description: "Active hearing protection with electronic sound amplification and communication input for tactical ops.", specs: [{ label: "NRR", value: "25 dB" }, { label: "Amplification", value: "4x (12 dB)" }, { label: "Battery", value: "2x AAA" }, { label: "Weight", value: "265g" }], features: ["Auto compression", "3.5mm audio input", "Gel ear seals", "Foldable design"] },
  { id: "13", slug: "mk19-grenade-launcher", name: "MK19 Grenade Launcher", category: "Firearms", image: "https://placehold.co/600x400/0a0a0a/333?text=MK19+Launcher", description: "Fully automatic belt-fed grenade launcher for vehicle-mounted or tripod use.", specs: [{ label: "Caliber", value: "40x53mm" }, { label: "Weight", value: "34 kg" }, { label: "Rate of Fire", value: "325-375 rpm" }, { label: "Range", value: "2200m" }], features: ["Vehicle mountable", "Tripod compatible", "Blowback operated", "Belt-fed"] },
  { id: "14", slug: "surefire-m600df", name: "SureFire M600DF Scout", category: "Tactical Supplies", image: "https://placehold.co/600x400/0a0a0a/333?text=SureFire+Scout", description: "Dual-fuel weaponlight delivering 1500 lumens with multiple power settings for tactical use.", specs: [{ label: "Output", value: "1500/300 lumens" }, { label: "Runtime", value: "1.5/7h" }, { label: "Beam Distance", value: "265m" }, { label: "Weight", value: "96g" }], features: ["Picatinny mount", "Dual fuel", "TIR lens", "Mil-Spec anodized"] },
  { id: "15", slug: "pvs-14-nvg", name: "AN/PVS-14 Night Vision", category: "Optics", image: "https://placehold.co/600x400/0a0a0a/333?text=PVS-14+NVG", description: "Third-generation monocular night vision device for night operations.", specs: [{ label: "Generation", value: "Gen III" }, { label: "Magnification", value: "1x" }, { label: "Detection Range", value: "300m" }, { label: "Battery Life", value: "40h" }], features: ["Head mount compatible", "Weapon mountable", "IR illuminator", "Auto shut-off"] },
  { id: "16", slug: "fast-ballistic-helmet", name: "FAST Ballistic Helmet", category: "Defense Apparel", image: "https://placehold.co/600x400/0a0a0a/333?text=FAST+Helmet", description: "NIJ IIIA rated high-cut tactical helmet with NVG shroud and rail system.", specs: [{ label: "Protection", value: "NIJ IIIA" }, { label: "Shell", value: "UHMWPE" }, { label: "Weight", value: "0.9 kg" }, { label: "Sizes", value: "S/M/L/XL" }], features: ["NVG shroud", "ARC rail system", "BOA retention", "Pad suspension"] },
  { id: "17", slug: "cat-gen7-tourniquet", name: "CAT Gen-7 Tourniquet", category: "Tactical Supplies", image: "https://placehold.co/600x400/0a0a0a/333?text=CAT+Tourniquet", description: "The most widely used tourniquet in the U.S. military for hemorrhage control.", specs: [{ label: "Application Width", value: "1.5 inch" }, { label: "Max Circumference", value: "8 inch" }, { label: "Windlass", value: "Reinforced plastic" }, { label: "Weight", value: "65g" }], features: ["One-handed application", "Time indicator", "Free-moving band", "Locking mechanism"] },
  { id: "18", slug: "m18-smoke-grenade", name: "M18 Smoke Grenade", category: "Ammunition", image: "https://placehold.co/600x400/0a0a0a/333?text=M18+Smoke", description: "Military-grade smoke grenade for signaling, obscuration, and target marking.", specs: [{ label: "Burn Time", value: "50-90 seconds" }, { label: "Colors", value: "Red/Green/Yellow/Violet" }, { label: "Weight", value: "0.539 kg" }, { label: "Diameter", value: "66mm" }], features: ["High visibility smoke", "Spoon safety", "Pull-ring fuze", "Mil-Spec"] },
  { id: "19", slug: "safariland-ankle-holster", name: "Safariland 295 Ankle Holster", category: "Tactical Supplies", image: "https://placehold.co/600x400/0a0a0a/333?text=Ankle+Holster", description: "Concealable ankle holster with self-contained retention strap for compact firearms.", specs: [{ label: "Material", value: "SafariLaminate" }, { label: "Closure", value: "Retention strap" }, { label: "Compatibility", value: "Glock 17/19/23/26" }, { label: "Leg Sizes", value: "S/M/L" }], features: ["Suede lining", "Neoprene leg band", "Velcro leg strap", "Ambidextrous"] },
  { id: "20", slug: "511-rush72-backpack", name: "5.11 RUSH72 Backpack", category: "Tactical Supplies", image: "https://placehold.co/600x400/0a0a0a/333?text=RUSH72+Pack", description: "Large-capacity tactical backpack for 72-hour operations with MOLLE webbing.", specs: [{ label: "Capacity", value: "55L" }, { label: "Material", value: "1050D Nylon" }, { label: "Weight", value: "1.9 kg" }, { label: "Dimensions", value: "61x36x30cm" }], features: ["MOLLE webbing", "Sleeping bag compartment", "Hydration compatible", "Admin panel"] },
];